name: Publish Docker Images (on push to main)

on:
  push:
    branches: ['main']
  workflow_dispatch: ~

env:
  GHCR_REGISTRY: ghcr.io/Milkshak3s
  GHCR_IMAGE_NAME: frps-controller-rs

jobs:
  build_push_controller:
    name: 🚀 Build & push controller image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: 🛠️ Setup Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: '1.76.0'
          default: true
          profile: minimal
      - name: ⚡ Setup Rust (x86_64-unknown-linux-musl)
        run: |
          rustup target add x86_64-unknown-linux-musl && \
          sudo apt update && \
          sudo apt install -y musl-tools
      - name: rust-cache
        uses: Swatinem/rust-cache@v2
      - name: 🔨 Build Controller
        run: cargo build --release
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.GHCR_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.GHCR_REGISTRY }}/${{ env.GHCR_IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=sha,format=long
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}